---
# Task 01 Part 01 - Creation
- name: Create Disk 1
  gcp_compute_disk:
    name: 'disk-instance-01'
    size_gb: 30
    source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes: 
      - https://www.googleapis.com/auth/compute
    state: present
  register: disk1
- name: Create Address 1
  gcp_compute_address:
    name: 'address-instance-01'
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: address1
- name: Create Instance 1
  gcp_compute_instance:
    state: present
    name: ansible-apache-01
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk1 }}"
    network_interfaces:
      - network: null 
        access_configs:
        - name: 'External NAT'
          nat_ip: "{{ address1 }}"
          type: 'ONE_TO_ONE_NAT'
    tags:
      items:
        - http-server
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance1
- name: Wait for SSH to come up
  wait_for: host={{ address1.address }} port=22 delay=10 timeout=60
- name: Add host to groupname
  add_host:
    hostname: '{{ address1.address }}'
    groupname: new_instances
# Instance 02
- name: Create Disk 2
  gcp_compute_disk:
    name: 'disk-instance-02'
    size_gb: 30
    source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: disk2
- name: Create Address 2
  gcp_compute_address:
    name: 'address-instance-02'
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: address2
- name: Create Instance 2
  gcp_compute_instance:
    state: present
    name: ansible-apache-02
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk2 }}"
    network_interfaces:
      - network: null 
        access_configs:
          - name: 'External NAT'
            nat_ip: "{{ address2 }}"
            type: 'ONE_TO_ONE_NAT'
    tags:
      items:
        - http-server
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance2
- name: Wait for SSH to come up
  wait_for: host={{ address2.address }} port=22 delay=10 timeout=60
- name: Add host to groupname
  add_host: 
    hostname: '{{ address2.address }}'
    groupname: new_instances